services:
  sj-dev-web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/server-entrypoint.sh
    container_name: sj-dev
    ports:
      - "8000"
    env_file:
      - ./.env
    volumes:
      # Static files
      - static_sj_dev:/app/staticfiles
      # Database files
      - /home/admsqline/projects/data/sj_dev:/app/data
    networks:
      - proxynet

  sj-dev-worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/worker-entrypoint.sh
    container_name: sj-dev-worker
    env_file:
      - ./.env
    volumes:
      # Static files
      - static_sj_dev:/app/staticfiles
    depends_on:
      - sj-dev-web
      - sj-dev-redis
    networks:
      - proxynet


  sj-dev-redis:
    restart: unless-stopped
    image: redis:8.0.3-alpine
    container_name: sj-dev-redis
    expose:
        - 6379
    networks:
      - proxynet

volumes:
  static_sj_dev:
    external: true

networks:
  proxynet:
    name: proxynet
    external: true
