services:
  sj-dev-web:
    build: .
    container_name: sj-dev
    ports:
      - "8000"
    env_file:
      - ./.env
    volumes:
      # Static files
      - static_sj_dev:/app/staticfiles
      # Database files
      - /home/admsqline/projects/data/sj_dev:/app/data
    networks:
      - proxynet

volumes:
  static_sj_dev:
    external: true

networks:
  proxynet:
    name: proxynet
    external: true
