services:
  sj-prd-web:
    build: .
    container_name: sj-prd
    ports:
      - "8000"
    env_file:
      - ./.env
    volumes:
      # Source code
      - static_sj_prd:/app/staticfiles
      # Database files
      - /home/admsqline/projects/data/sj_prd:/app/data
    networks:
      - proxynet

volumes:
  static_sj_prd:
    external: true

networks:
  proxynet:
    name: proxynet
    external: true
