services:
  sj-prd-web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/server-entrypoint.sh
    container_name: sj-prd
    ports:
      - "8000"
    env_file:
      - ./.env
    volumes:
      # Source code
      - static_sj_prd:/app/staticfiles
      # Database files
      - /home/admsqline/projects/data/sj_prd:/app/data
    networks:
      - proxynet

  sj-prd-worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/worker-entrypoint.sh
    container_name: sj-prd-worker
    env_file:
      - ./.env
    volumes:
      # Static files
      - static_sj_prd:/app/staticfiles
      # Database files
      - /home/admsqline/projects/data/sj_prd:/app/data
    depends_on:
      - sj-prd-web
      - sj-prd-redis
    networks:
      - proxynet

  sj-prd-redis:
    restart: unless-stopped
    image: redis:8.0.3-alpine
    container_name: sj-prd-redis
    expose:
        - 6379
    networks:
      - proxynet

volumes:
  static_sj_prd:
    external: true

networks:
  proxynet:
    name: proxynet
    external: true
