# Generated by Django 4.1.5 on 2023-05-01 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sj_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(default='', max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_active', models.BooleanField(default=False, verbose_name=True)),
                ('event_reg_open', models.BooleanField(default=False, verbose_name=True)),
                ('event_reg_start', models.DateTimeField()),
                ('event_reg_end', models.DateTimeField()),
                ('event_num_lines', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='sj_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('byear', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=1)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('startnum', models.IntegerField(default=0)),
                ('state', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sj_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('run_nr', models.IntegerField(default=0)),
                ('line_nr', models.IntegerField(default=0)),
                ('result', models.FloatField(default=-1)),
                ('result_category', models.CharField(default='', max_length=3)),
                ('state', models.CharField(choices=[('SQR', 'set for qualy run'), ('RQR', 'result qualy run'), ('SFN', 'set for final run'), ('RFN', 'result final run'), ('DNF', 'did not finish')], default='DNF', max_length=3)),
                ('fk_sj_events', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.sj_events')),
                ('fk_sj_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.sj_users')),
            ],
        ),
    ]
