# Generated by Django 4.2.1 on 2023-05-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_sj_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sj_users',
            name='gender',
            field=models.CharField(choices=[('W', 'weiblich'), ('M', 'männlich')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='sj_users',
            name='state',
            field=models.CharField(choices=[('W', 'weiblich'), ('M', 'männlich')], default='', max_length=10),
        ),
    ]
