# Generated by Django 4.2 on 2024-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_sj_users_admin_state_alter_sj_users_byear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sj_events',
            name='event_active',
            field=models.BooleanField(default=False, verbose_name='Event aktiv'),
        ),
        migrations.AlterField(
            model_name='sj_events',
            name='event_date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='sj_events',
            name='event_name',
            field=models.CharField(default='', max_length=50, verbose_name='Anlass'),
        ),
        migrations.AlterField(
            model_name='sj_events',
            name='event_num_lines',
            field=models.IntegerField(default=4, verbose_name='Anzahl Bahnen'),
        ),
        migrations.AlterField(
            model_name='sj_events',
            name='event_reg_end',
            field=models.DateTimeField(verbose_name='Registration bis'),
        ),
        migrations.AlterField(
            model_name='sj_events',
            name='event_reg_open',
            field=models.BooleanField(default=False, verbose_name='Registration aktiv'),
        ),
        migrations.AlterField(
            model_name='sj_events',
            name='event_reg_start',
            field=models.DateTimeField(verbose_name='Registration ab'),
        ),
    ]
