# Generated by Django 5.2.4 on 2025-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_sj_results_result_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sj_users',
            name='admin_state',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sj_users',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
