# Generated by Django 5.2.16 on 2026-07-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_sj_users_admin_state_alter_sj_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sj_events',
            name='event_program',
            field=models.TextField(blank=True, default='', verbose_name='Event Programm'),
        ),
    ]
