# Generated by Django 5.2.16 on 2026-08-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_sj_events_event_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='sj_events',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ort'),
        ),
    ]
